### PR TITLE
Allow ConnectQuery to be aborted

### PR DESCRIPTION
**Pull request by bholdt**

### CODE REVIEW

**Comment by chadedrupt** [comment]
Looks good mate :+1:

**Comment by AdamPD** [comment]
Looks good but I wonder if we should allow a specific execution to be cancelled too? Does Q not have cancelling functionality out of the box?

**Comment by chadedrupt** [comment]
What do you mean by allow a "specific execution to be cancelled"? @AdamPD 

A call to `abortAll` would cancel any pending HTTP requests. 
The promises would not be fulfilled. 

Do you think we should be rejecting? 

The more I talk about it the more I realise you can't leave them un-fulfilled :smile:

**Comment by bholdt** [comment]
Yeah, we should probably reject promise. You cannot cancel a QPromise though

Q docs:
`in short, Q will not implement cancellation on promises`

**Comment by AdamPD** [comment]
Yea I don't think we can leave them unfulfilled. I mean abortAll will abort all executions of a particular query, whereas that may not be the desired behaviour.

Also - are the queries immutable? So if you modify them consequently and then abort you don't abort previous queries.

I'd rather somehow cancel the promise itself rather than the query object.

**Comment by chadedrupt** [comment]
Yeah, the only time `abortAll` will abort multiples is if you have multiple calls to `execute` without modifying the query. I feel that it likely is the intended behaviour.

**Comment by bholdt** [comment]
How about passing in a cancellation token to execute() as an optional parameter.
client can say. cancellationToken.cancel(), which then rejects the promise and aborts underlying request.

**Comment by chadedrupt** [comment]
I feel that you can't have `execute` return anything other than a promise.

What @bholdt is suggesting is another alternative.

Which do we feel is better?:

``` javascript
const query = connect.query("purchases")
    .select({ "totalPrice": { "sum": "price" } });

query.execute()
    .then(function(result) {
        // Handle the result
    }, function(error) {
      // Handle an error
    });

query.abort();

// Or

const cancelationToken = Connect.CancelationToken();

connect.query("purchases")
    .select({ "totalPrice": { "sum": "price" } });
    .execute(cancelationToken)
        .then(function(result) {
            // Handle the result
        }, function(error) {
            // Handle an error
        });

cancelationToken.cancel();
```

Personally I still think the first

**Comment by bholdt** [comment]
Ok. Changed to function name to abort, and rejecting promise and aborting underlying requests when query is still running.

**Comment by chadedrupt** [comment]
:+1:

**Comment by mattfurness** [comment]
+1

**Comment by mattfurness** [comment]
:+1:

**Pull request merged**
